active_set: dcase2018_baseline

sets:
  # DCASE2018 baseline
  # ================================
  - set_id: dcase2018_baseline
    description: DCASE2018 baseline / Development setup
    dataset:
      method: baseline_development

  - set_id: dcase2018_baseline_eval
    description: DCASE2018 baseline / Evaluation setup
    path:
      application:
        feature_extractor: eval_features
        recognizer: eval_recognizer

    dataset:
      method: baseline_evaluation

  - set_id: dcase2018_baseline_leaderboard
    description: DCASE2018 baseline / Leader board setup
    path:
      application:
        feature_extractor: leaderboard_features
        recognizer: leaderboard_recognizer

    dataset:
      method: baseline_leaderboard

defaults:
  flow:
    feature_extraction: true
    feature_normalization: true
    learning: true
    testing: true
    evaluation: true

  general:
    overwrite: false                        # Overwrite previously stored data
    active_fold_list: !!null                # List of active folds

  path:
    dataset: datasets/
    log: log/
    application:
      base: system/task1a
      feature_extractor: features
      feature_normalizer: normalization
      learner: learner
      recognizer: recognizer
      evaluator: evaluator

  dataset:
    method: baseline_development

  dataset_method_parameters:
    baseline_development:
      dataset: TUTUrbanAcousticScenes_2018_DevelopmentSet
      evaluation_mode: folds

    baseline_evaluation:
      dataset: TUTUrbanAcousticScenes_2018_EvaluationSet
      evaluation_mode: full

    baseline_leaderboard:
      dataset: TUTUrbanAcousticScenes_2018_LeaderboardSet
      evaluation_mode: full

  feature_extractor:
    method: mel
    win_length_seconds: 0.04
    hop_length_seconds: 0.02
    fs: 44100

  feature_extractor_method_parameters:
    mel:
      spectrogram_type: magnitude
      window_type: hamming_asymmetric
      n_mels: 128
      n_fft: 2048
      fmin: 0
      fmax: 22050
      htk: false
      normalize_mel_bands: false

  data_processing_chain:
    method: sequencing_chain

  data_processing_chain_method_parameters:
    sequencing_chain:
      chain:
        - processor_name: dcase_util.processors.FeatureReadingProcessor

        - processor_name: dcase_util.processors.NormalizationProcessor
          init_parameters:
            enable: true

        - processor_name: dcase_util.processors.SequencingProcessor
          init_parameters:
            sequence_length: 500
            hop_length: 500

        - processor_name: dcase_util.processors.DataShapingProcessor
          init_parameters:
            axis_list:
              - sequence_axis
              - data_axis
              - time_axis

  meta_processing_chain:
    method: one_hot

  meta_processing_chain_method_parameters:
    one_hot:
      chain:
        - processor_name: dcase_util.processors.OneHotEncodingProcessor

  learner:
    method: rcnn

  learner_method_parameters:
    rcnn:
      random_seed: 0
      keras_profile: cuda0_fast
      backend: tensorflow

      validation_set:
        enable: true
        validation_amount: 0.2
        balancing_mode: identifier_two_level_hierarchy
        seed: 0

      data:
        data_format: channels_last
        target_format: single_target_per_sequence

      generator:
        enable: false

      model:
        constants:
          CONVOLUTION_INIT: glorot_uniform
          CONVOLUTION_KERNEL_SIZE: 7
          CONVOLUTION_ACTIVATION: relu
          CONVOLUTION_DROPOUT: 0.3
          CONVOLUTION_BORDER_MODE: same

          DATA_FORMAT: channels_last

        config:
          - class_name: LSTM
            config:
              input_shape:
                - FEATURE_VECTOR_LENGTH   # data_axis
                - INPUT_SEQUENCE_LENGTH   # time_axis
                - 1
              units: 128
              return_sequences: True

          - class_name: LSTM
            config:
              units: 128
              return_sequences: True

          # Drop out layer
          - class_name: Dropout
            config:
              rate: 0.5

          #Time Distributed
          - class_name: TimeDistributed
            config:
              - class_name: Dense
                config:
                  units: 64
                  kernel_initializer: uniform
                  activation: CONVOLUTION_ACTIVATION

          #Time Distributed
          - class_name: TimeDistributed
            config:
              - class_name: Dense
                config:
                  units: 32
                  kernel_initializer: uniform
                  activation: CONVOLUTION_ACTIVATION

          #Time Distributed
          - class_name: TimeDistributed
            config:
              - class_name: Dense
                config:
                  units: 16
                  kernel_initializer: uniform
                  activation: CONVOLUTION_ACTIVATION

          #Time Distributed
          - class_name: TimeDistributed
            config:
              - class_name: Dense
                config:
                  units: 8
                  kernel_initializer: uniform
                  activation: CONVOLUTION_ACTIVATION

          # Flatten
          # ====================================
          - class_name: Flatten

          # Output layer
          # ====================================
          - class_name: Dense
            config:
              units: CLASS_COUNT
              kernel_initializer: uniform
              activation: softmax

      compile:
        loss: categorical_crossentropy
        metrics:
          - categorical_accuracy

      optimizer:
        class_name: Adam

      fit:
        epochs: 200
        batch_size: 16
        shuffle: True

      callbacks:
        StasherCallback:
          monitor: val_categorical_accuracy
          initial_delay: 50

  recognizer:
    frame_binarization:
      enable: true
      threshold: 0.5
      type: global_threshold